name: Build Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  backend-build-and-test:
    runs-on: ubuntu-latest
    name: Backend Build and Test
    
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
          - 1433:1433
        env:
          ACCEPT_EULA: "Y"
          SA_PASSWORD: ${{ secrets.TEST_DB_SA_PASSWORD }}
        options: --health-cmd="exit 0" --health-interval=10s --health-timeout=5s --health-retries=3
      rabbitmq:
        image: masstransit/rabbitmq
        ports:
          - 5672:5672

    env:
        ConnectionStrings__DefaultConnection: "Server=localhost,1433;Database=TodoItems.Test;User Id=sa;Password=${{ secrets.TEST_DB_SA_PASSWORD }};TrustServerCertificate=True;"
        Logging__LogLevel__Default: "Information"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          cache: true
          cache-dependency-path: ./**/packages.lock.json

      - name: Restore
        run: |
          dotnet restore

      - name: Build
        run: |
          dotnet build --no-restore --configuration Release

      - name: Test
        run: |
          dotnet test --no-build --no-restore --configuration Release --logger "console;verbosity=detailed" --logger trx --results-directory "TestResults"
    
      - uses: actions/upload-artifact@v4
        with:
          name: dotnet-test-results
          path: TestResults
          